version: 2

sphinx:
  configuration: docs/conf.py

python:
  version: "3.12"
  install:
    - requirements: docs/requirements.txt

apt_packages:
  - doxygen

build:
  commands:
    - cd docs
    - doxygen Doxyfile
